Work in progress setting up a flat ODC loader for the GeoMAD
digitalearthpacific/dep-tools pull request #20
Opened 2023-11-07 05:19 UTC by alexgleith

2023-11-09 20:29 UTC, jessjaco commented
Just did a quick review. Things look good. I'm thinking we could combine the 2 odc loaders - either add a param `return_type` which defines the return type, or have the existing odcloader subclass the flat loader.  I prefer to not have duplicated code if we can help it.

Happy to help with that part, when the interface is stable.

2023-11-09 20:37 UTC, alexgleith commented
Yeah, good idea. Should be easy to do.

Then we can parameterise the structure and returned data type, which should provide some good flexibility.

2023-11-13 22:42 UTC, jessjaco commented
I like adding the odc writer. I'm thinking about making a separate mixin for odc vs rioxarray writing (not unlike the structure in the loaders), so as not to have to pass more args through to write_to_blob_storage. Sound good?

2023-11-13 22:50 UTC, alexgleith commented
Yeah, that works I guess.

I think there'll be more code duplication that way though, won't there?

2023-11-15 21:00 UTC, alexgleith commented
Nice! Although that's still not doing the kind of logging I'm after, I'm sure I can create another variant that does.

We almost need a week long workshop to get this tooling working better!

I'm on hold while I wait for our infrastructure to come back online, but when it has and I have done some test runs of the geomad, I'll come back and break this out into a bunch of smaller PRs... and using your proposed task runner sounds good.

2023-11-15 21:05 UTC, jessjaco commented
That's what I was thinking...just make a Task that has whatever logging you want

2023-11-17 06:33 UTC, alexgleith commented
> Although that's still not doing the kind of logging I'm after

I have an idea around logging and "have we done this already" checking, which I can implement later.

2023-11-17 23:38 UTC, jessjaco requested changes

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/utils.py
> +    cell: A GeoDataFrame.
`cell` is confusing here. This is a generic function, I  think we should leave the param name generic too

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/utils.py
> +    else:
No love for my R-style return logic? I can live with that.

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/utils.py
> +        client = get_container_client()
What happened to my kwargs

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/utils.py
> +        client = get_container_client()
I guess, if you're going to add client as an arg, just drop the kwargs

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/writers.py
> +        with ThreadPoolExecutor() as executor:
If xr is a lazy dask array (how I try to work in almost all my processing), won't this muck up the scheduler  (since the data aren't processed until write)? 

Also,  writes can occasionally be memory bound and if we're doing them concurrently it could make it worse. 

I also wonder if some of the slowdown you were seeing is because you were testing locally?

Finally, it's also worth considering the processing here, if even generically. If variables within a dataset are derivatives of the same data, then loading variables independently may incur multiple reads of the same source data (because dask / xarray has no way of knowing the data have already been loaded in another variable). Early on when I was performance focused one of the reasons I was writing multiband tiffs was it reduced the number of network reads. I did run into other issues with this approach (I have old notes somewhere), but if you are indeed going to load all the data concurrently maybe just call xr.load() first so it can maybe gain some of these improvements

At the very least, we need a way to opt out of this

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/s2_utils.py
> +    # SNOW = 11
I'm guessing your linter didn't like these unused variables?

2023-11-17 23:38 UTC, jessjaco commented on dep_tools/s2_utils.py
> +        cloud_mask = mask_cleanup(cloud_mask, [("opening", 2), ("dilation", 3)])
Would be nice, at some point to condense logic that is reused from landsat_utils

2023-11-18 15:58 UTC, jessjaco commented on dep_tools/writers.py
> +        with ThreadPoolExecutor() as executor:
And another thought I had last night: the single band writes of the (multiband) dataset might be why it looks why it's running multiple times

2023-11-19 21:12 UTC, alexgleith commented on dep_tools/writers.py
> +        with ThreadPoolExecutor() as executor:
> might be why it looks why it's running multiple times

Good point. But I don't think that is what was happening. The GeoMAD loads everything into memory as part of the processing and also, the dask graph I was watching was loading red, green, blue, ... all the bands.

> At the very least, we need a way to opt out of this

This is probably a good idea. Although, I think it's much more likely to be memory bound earlier in the processing, and from what I have seen, concurrent writing is much more efficient than sequential. Agree it might not be the case for all products. Also I do think forcing an `xr = xr.compute()` is a really good idea just before writing... unless we really optimise dask writing.

2023-11-19 21:12 UTC, alexgleith commented on dep_tools/s2_utils.py
> +    # SNOW = 11
Yeah! We can keep them exposed if you want, it's not a big deal. It _is_ nice documentation having them there!

2023-11-19 21:14 UTC, alexgleith commented on dep_tools/utils.py
> +    else:
Just aiming for readability.

I like having a single return statement normally, so having logic that results in the same return statement running. Having return statements in the middle of a function can be hard to follow.

This change was just me aiming for low cognitive load for future alex (and jesse)!

2023-11-19 21:15 UTC, alexgleith commented on dep_tools/namers.py
> +    def _format_item_id(self, item_id, join_str="/") -> str:
Yeah, I agree.

This was getting a bit messy and opinionated for sure.

I like your solution here.

2023-11-19 21:16 UTC, alexgleith commented on dep_tools/loaders.py
> +        data_type = "uint16" if self.keep_ints else "float32"
Since these loaders are specific to Landsat or Sentinel, there's not really going to be any other data types.

If we build a generic product loader, then perhaps we need more flexibility.

2023-11-19 21:18 UTC, alexgleith commented on dep_tools/loaders.py
> +        # from the server in the first place.
We can do a query like `"query={"platform":{"in":["landsat-9", "landsat-8"]}}"`

Does your syntax work?

The way I've done that query is like `query={"landsat:collection_category": {"in": ["T1"]}}`

2023-11-19 21:24 UTC, alexgleith commented on dep_tools/landsat_utils.py
> +    xr: DataArray, dilate: Tuple[int, int] | None = None, keep_ints: bool = False
Yeah, I agree here.

I'm torn between following the way the ODC folks do it (like you suggest) `[["opening", 5], ["dilation", 5]]` or just being opinionated and having True/False.

I think having it changeable is important... so we should use the same API as them. Maybe instead of `None` as a default, we have what we're using, so if you don't want to make a call, it masks clouds the "right" way.

2023-11-19 21:25 UTC, alexgleith commented on dep_tools/namers.py
> +    def _format_item_id(self, item_id, join_str="/") -> str:
The ODC folks have a parameter for region code formatting like `"x{x:03d}y{y:03d}"`

2023-11-19 23:11 UTC, jessjaco commented on dep_tools/loaders.py
> +        data_type = "uint16" if self.keep_ints else "float32"
But this is a generic loader. I've intended it that way and have already used it to load our own data: https://github.com/digitalearthpacific/dep-wofs/blob/4fd9555f37e0e2118ef5230c64662392395c87a6/src/mask.py#L21

2023-11-19 23:11 UTC, jessjaco commented on dep_tools/loaders.py
> +        # from the server in the first place.
OK, I just wasn't familiar with the syntax enough

2023-11-19 23:11 UTC, jessjaco commented on dep_tools/writers.py
> +        with ThreadPoolExecutor() as executor:
I don't want to enforce a compute, because ideally the tooling should reach a point where it can read, process, and write chunk by chunk. So only a chunk of input and output data is in memory at once. The choking point currently is the need to write to memory before copying to azure, but the new s3 writing for example, offers a way out of that.

I agree about concurrent writing. That's why I was writing multiband tiffs. However, this solution still makes me nervous

2023-11-19 23:16 UTC, alexgleith commented on dep_tools/loaders.py
> +        data_type = "uint16" if self.keep_ints else "float32"
Oh, you're right sorry.

I guess we should sit and look at this. The `odc-stac` load function has a range of parameters that we should really not be re-implementing.

2023-11-19 23:21 UTC, alexgleith commented on dep_tools/loaders.py
> +        # from the server in the first place.
Yeah, it's not easy to discover!

2023-11-19 23:22 UTC, alexgleith commented on dep_tools/loaders.py
> +        data_type = "uint16" if self.keep_ints else "float32"
The example config from ODC STAC is here at the bottom of the page: https://odc-stac.readthedocs.io/en/latest/_api/odc.stac.load.html

2023-11-26 22:47 UTC, alexgleith commented on dep_tools/landsat_utils.py
> +        return erase_bad(xr, cloud_mask)
I think we should ensure we load data with nodata set properly, then we can assume it's set everywhere else.

For this to work we need to be consistent, of course... to be discussed.

2023-11-26 23:29 UTC, alexgleith commented on dep_tools/loaders.py
> +        # from the server in the first place.
Added filter logic and tests.

2023-11-26 23:32 UTC, alexgleith commented on dep_tools/loaders.py
> +        data_type = "uint16" if self.keep_ints else "float32"
I think we need to leave this one for later.

The best way to handle this is to pass the datatype config straight through to the odc loader and to not do logic around `nan` or `int` masking here, I think.

2023-11-26 23:36 UTC, alexgleith commented on dep_tools/namers.py
> +    def _format_item_id(self, item_id, join_str="/") -> str:
Tweaked this a bit to pass through strings.

We need to refactor to do this right.

2023-11-26 23:38 UTC, alexgleith commented on dep_tools/processors.py
> +        keep_ints: bool = False
The intention is that this handles ints, but doesn't assume that they are ints.

2023-11-26 23:40 UTC, alexgleith commented on dep_tools/runner.py
> +    def run_one(self, index):
Ok, will remove these changes.

2023-11-26 23:42 UTC, alexgleith commented on dep_tools/utils.py
> +    cell: A GeoDataFrame.
Changed "cell" to "region"

2023-11-26 23:43 UTC, alexgleith commented on dep_tools/utils.py
> +        client = get_container_client()
Good point. Added kwargs back in for the container client getting.

2023-11-26 23:51 UTC, alexgleith commented on dep_tools/writers.py
> +        with ThreadPoolExecutor() as executor:
Ok, added a fallback.

The multi-threaded writing worked brilliantly though! Simple and effective :-)

2023-11-26 23:53 UTC, alexgleith commented on dep_tools/landsat_utils.py
> +        return erase_bad(xr, cloud_mask)
I'll lift this out as an issue.

2023-11-27 17:34 UTC, jessjaco commented on dep_tools/task.py
> +        paths = self.writer.write(output_data, self.id, multithreaded=self.multithreaded)
We can't do this, multithreaded is not part of the Writer class

2023-11-27 17:35 UTC, jessjaco commented on dep_tools/writers.py
> +    def write(self, xr: Dataset, item_id: str, multithreaded: bool = False) -> Union[str, List]:
`multithreaded` should be a class var or it breaks the abstraction

2023-11-27 17:49 UTC, jessjaco commented on dep_tools/writers.py
> +                        driver="COG", nodata=output_da.attrs.get("nodata", None)
This is already the default value for nodata, see https://odc-geo.readthedocs.io/en/latest/_api/odc.geo.xr.to_cog.html

2023-11-27 17:52 UTC, jessjaco commented on dep_tools/writers.py
> +                        driver="COG", nodata=output_da.attrs.get("nodata", None)
Also, I will remove the driver="COG" default on next go around, I want to sound a warning

2023-11-27 21:43 UTC, jessjaco commented
Ok, I made some changes which needed to happen and some to improve clarity. I'm still not totally settled on the loader in particular, but also would like to refactor the write_to_blob_storage function. However, I think these can be best handled piecewise

2023-11-27 21:55 UTC, alexgleith commented
Looks clean! Nice work, especially with the partial function. That's neat.

2023-11-28 00:32 UTC, jessjaco commented
Pending any further input, I'd like to merge this tomorrow and relegate fixes or additional changes to new PRs

2023-11-28 02:08 UTC, alexgleith commented
Happy for you to merge it in.

2023-11-28 21:38 UTC, merged

2023-11-28 23:16 UTC, jessjaco commented on dep_tools/namers.py
> +    def _format_item_id(self, item_id, join_str="/") -> str:
I need to fix this. Can you tell me what things you want to pass in so I can test them all? I'm guessing 
"1,2" [should be "001_002"]
("1,2", FJ) [should be "001_002_FJ"] <- are you still doing this?

I need to pass in e.g. (1,2) and it's not working